Citizen.CreateThread(function()
	while true do
		-- Citizen.Wait(300000)
		-- TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Para mostrar tu numero de telefono en un movil tienes que poner /telfix.")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "El uso inadecuado del chat conlleva una expulsion del servidor.")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Reporta cualquier bug en nuestro discord discord.gg/atenas")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Visita nuestra web - atenasrp.com")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Puedes visitar nuestro concesionario abriendo el mapa y buscando el simbolo de un coche blanco. ")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Si tienes algun problema puedes mandar /report y un administrador te ayudará.")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Recuerda antes de hacer alguna acion ilegal mandar /entorno")
		Citizen.Wait(300000)
		TriggerEvent('chatMessage', 'ATENAS COMMUNITY', {20, 245, 170}, "Para llamar a un EMS puedes usar /auxilio")
	end
end)